# SwiftLint Configuration pour ARCode Clone
# Règles strictes pour qualité de code

disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - vertical_parameter_alignment_on_call
  - yoda_condition

included:
  - Sources
  - Tests

excluded:
  - Pods
  - .build
  - DerivedData

line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 400

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level: 2
  function_level: 3

identifier_name:
  min_length: 2
  max_length: 60

type_name:
  min_length: 3
  max_length: 50

reporter: "xcode"











